name: Deploy Sanity Studio (hosted)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "sanity.config.ts"
      - "sanity.cli.ts"
      - "sanity/**"
      - ".github/workflows/deploy-studio.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install minimal deps
        run: npm i --no-audit --no-fund sanity @sanity/vision

      - name: Show target
        run: |
          echo "Deploying Studio to https://${{ secrets.SANITY_STUDIO_HOST }}.sanity.studio"

      - name: Sanity check
        run: npx --yes sanity@latest check

      - name: Deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: npx --yes sanity@latest deploy "${{ secrets.SANITY_STUDIO_HOST }}" --yes
