name: Deploy Sanity Studio (hosted)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "sanity.config.ts"
      - "sanity/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/deploy-studio.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Prepare deps (Studio only)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          elif [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          else
            npm init -y
            npm i --no-audit --no-fund sanity @sanity/vision
          fi

      - name: Deploy Studio to Sanity hosting
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
        run: npx --yes sanity@latest deploy ${{ secrets.SANITY_STUDIO_HOST }} --yes

